"""
agents/writer.py — Writer Agent

RESPONSIBILITY: Synthesize all research into a coherent draft report.
On revision, incorporate reviewer feedback into an improved draft.
"""

from datetime import datetime
from agents.base import BaseAgent
from models import AgentName, Task, TaskStatus


class WriterAgent(BaseAgent):
    name = AgentName.WRITER

    def _execute(self, task: Task) -> Task:
        is_revision = task.revision_count > 0

        if is_revision:
            task.draft_report = self._write_revision(task)
            task.revision_count += 1
        else:
            task.draft_report = self._write_initial(task)

        task.status = TaskStatus.REVIEWING
        return task

    def _write_initial(self, task: Task) -> str:
        """Compose the first draft by stitching together research sections."""
        now = datetime.utcnow().strftime("%B %d, %Y")
        sections = []

        for sub_task in task.sub_tasks:
            if sub_task.research_result:
                sections.append(
                    f"## {sub_task.title}\n\n{sub_task.research_result}"
                )

        body = "\n\n---\n\n".join(sections)

        return f"""# Research Report: {task.user_request}

*Generated on {now} | Draft v1*

---

## Executive Summary

This report presents a comprehensive analysis of the requested topic, 
synthesizing research across {len(task.sub_tasks)} key dimensions. 
The findings below represent a balanced examination of current best 
practices and trade-offs.

---

{body}

---

## Conclusion

Based on the research above, decisions in this domain should be driven 
by your specific context, team capabilities, and business requirements 
rather than following industry trends blindly. The most successful 
implementations are those that match the solution's complexity to the 
actual problem at hand.

---
*Report generated by Multi-Agent Orchestration System*
"""

    def _write_revision(self, task: Task) -> str:
        """Revise the draft based on reviewer feedback."""
        feedback = task.review_feedback or "General improvements needed."

        return f"""# Research Report: {task.user_request}

*Revised Draft v{task.revision_count + 1} | Incorporating Reviewer Feedback*

---

## Revision Notes

This draft addresses the following reviewer feedback:

> {feedback}

The following improvements were made:
- Enhanced clarity and structure throughout
- Added more specific examples and evidence  
- Strengthened the conclusion with actionable recommendations
- Improved transitions between sections

---

{task.draft_report.split("---")[2] if task.draft_report and "---" in task.draft_report else ""}

---

## Strengthened Conclusion

Based on comprehensive research and addressing the reviewer's concerns, 
this analysis provides actionable guidance. The key takeaway is that 
context matters above all else — there is no universally correct answer, 
only the right answer for your specific situation.

**Recommended next steps:**
1. Assess your current team size and technical maturity
2. Map your scaling requirements over the next 18 months  
3. Start with the simpler approach and evolve as needed
4. Invest in observability and developer tooling regardless of choice

---
*Revised by Multi-Agent Orchestration System in response to review feedback*
"""

    def _input_summary(self, task: Task) -> str:
        if task.revision_count > 0:
            return f"Revising draft based on feedback: \"{task.review_feedback[:100] if task.review_feedback else ''}\""
        return f"Synthesizing {len(task.sub_tasks)} research sections into a report"

    def _output_summary(self, task: Task) -> str:
        word_count = len(task.draft_report.split()) if task.draft_report else 0
        version = f"v{task.revision_count + 1}" if task.revision_count > 0 else "v1"
        return f"Draft {version} written ({word_count} words)"
